// Default production adapters + intercepted exact A2 wire fixtures. No real auth/LLM acceptance.
import {test,expect,type Page} from '@playwright/test';
import {deliveryView} from '../../a2-fixtures';
import {conversation,models,makeRun,makeItem,frame,now,ref,ok} from '../../fixtures';
async function backend(page:Page,mode:'normal'|'lost-accept'|'lost-submit'|'old-hash'|'cancel-race'|'missing'|'pagination'|'identity'='normal'){
 const state={turns:0,accepts:0,controls:0,hasRun:mode!=='lost-submit',receipt:false,cancelled:false,old:mode==='old-hash',session:'session-one',denied:false,original:'已有原文',cursorExpired:mode==='pagination',listReads:0};
 const failure=(code:string,message:string,kind='stale',category='conflict')=>({kind,failure:{code,category,message,retryable:false,failed_phase:'read'},output_refs:[]});
 await page.route('**/v1/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname;const run=()=>makeRun(state.cancelled?'cancelled':state.receipt?'completed':'waiting_for_user',state.receipt||state.cancelled?2:1);
 if(path==='/v1/web/session')return route.fulfill(state.denied?{status:403,json:failure('web_session_revoked','会话已撤销','denied','authorization')}:{json:ok({principal:{id:'user-one',kind:'user',auth_session_id:state.session},expires_at:now,csrf_token:'c'.repeat(64)})});
 if(path==='/v1/models')return route.fulfill({json:ok(models)});
 if(path==='/v1/conversations'&&req.method()==='GET'){state.listReads++;if(mode==='pagination'){if(url.searchParams.get('cursor')==='second'){if(state.cursorExpired){state.cursorExpired=false;return route.fulfill({status:412,json:failure('cursor_invalid','游标过期')});}return route.fulfill({json:ok({items:[{...conversation,id:'conv-two',title:'第二页历史'}],snapshot_revision:2})});}return route.fulfill({json:ok({items:[conversation],snapshot_revision:2,next_cursor:'second'})});}return route.fulfill({json:ok({items:[conversation],snapshot_revision:1})});}
 if(path==='/v1/conversations/conv-one'||path==='/v1/conversations/conv-two')return route.fulfill({json:ok({...conversation,id:path.split('/').at(-1)!})});
 if(path.endsWith('/turns')){state.turns++;state.original=req.postDataJSON().payload.text;state.hasRun=true;if(mode==='lost-submit')return route.abort('connectionfailed');return route.fulfill({status:202,json:ok(run())});}
 if(path.includes('/turn-requests/'))return route.fulfill({json:ok(run())});
 if(path.endsWith('/items')){const items=state.hasRun?[makeItem('user-one','user_message',state.original),makeItem('artifact-item','artifact','条目仅有摘要')]:[];if(items[1])items[1].resource_refs=[state.old?{...ref('artifact','artifact-one'),content_hash:'f'.repeat(64)}:ref('artifact','artifact-one')];return route.fulfill({json:ok({items,snapshot_revision:state.hasRun?2:1})});}
 if(path.endsWith('/events'))return route.fulfill({json:ok({items:state.hasRun?[{event_id:'event-one',stream_id:conversation.id,seq:1,type:'run.updated',schema_version:'0.1',occurred_at:now,payload_ref:ref('event','event-one')}]:[],snapshot_revision:1})});
 if(path.endsWith('/payload'))return route.fulfill({json:ok({action:'run.updated',parameters:run()})});
 if(path==='/v1/runs/run-one')return route.fulfill({json:ok(run())});
 if(path.endsWith('/frame'))return route.fulfill({json:ok(frame)});
 if(path.endsWith('/delivery')){if(mode==='missing')return route.fulfill({status:404,json:failure('record_missing','当前没有成果','missing','arguments')});const v=deliveryView(state.receipt);if(state.receipt)v.acceptance!.principal.auth_session_id=state.session;return route.fulfill({json:ok(v)});}
 if(path.endsWith('/acceptance')){state.accepts++;expect(req.headers()['x-uaw-csrf']).toBe('c'.repeat(64));const body=req.postDataJSON();expect(body.payload).toEqual({bundle_ref:ref('content','bundle-one'),artifact_ref:ref('artifact','artifact-one'),decision:'accept'});expect(body.meta.expected_revision).toBeUndefined();
  if(mode==='cancel-race'){state.cancelled=true;return route.fulfill({status:412,json:failure('run_cancelled','运行取消，接受已拒绝')});}
  if(state.session!=='session-one')return route.fulfill({status:403,json:failure('delivery_session_denied','历史成果不能借新登录接受','denied','authorization')});
  if(mode==='lost-accept')return route.abort('connectionfailed');state.receipt=true;return route.fulfill({json:ok(deliveryView(true).acceptance)});
 }
 if(path.endsWith('/control')){state.controls++;state.cancelled=true;return route.fulfill({json:ok({operation_id:'control-one',status:'accepted'})});}
 return route.fulfill({status:503,json:failure('capability_unavailable','fixture未实现','failed','dependency')});
 });return state;
}
async function open(page:Page){await page.goto('/');await expect(page.getByText('已连接 · 分页轮询')).toBeVisible();}
test('A2 default: server list, full text, requirement reasons and exact contract acceptance survive refresh',async({page})=>{const s=await backend(page);await open(page);await expect(page.getByLabel('成果侧栏').getByRole('heading',{name:'完整正文报告'})).toBeVisible();await expect(page.getByText('逐项核验理由')).toBeVisible();await expect(page.getByText('受控测试不证明实际模型质量')).toBeVisible();await page.getByRole('button',{name:'接受整份成果'}).click();await expect(page.getByText('实际阶段 · completed')).toBeVisible();await page.reload();await expect(page.getByText('实际合同决定：accept',{exact:false})).toBeVisible();expect(s.accepts).toBe(1);expect(s.turns).toBe(0);await page.screenshot({path:'.test-results/u2-full-delivery.png',fullPage:true});});
test('A2 default: unknown acceptance stays blocked after reload until actual receipt exists',async({page})=>{const s=await backend(page,'lost-accept');await open(page);await expect(page.getByRole('button',{name:'接受整份成果'})).toBeEnabled();await page.getByRole('button',{name:'接受整份成果'}).click();await expect(page.getByText('接受结果未知；只查询实际 acceptance，无回执不重发。')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'接受整份成果'})).toBeDisabled();await page.getByRole('button',{name:'读取当前成果与接受回执'}).click();expect(s.accepts).toBe(1);s.receipt=true;await page.getByRole('button',{name:'读取当前成果与接受回执'}).click();await expect(page.getByText('实际合同决定：accept',{exact:false})).toBeVisible();expect(s.accepts).toBe(1);});
test('A2 default: lost submit refresh looks up original request and never resubmits',async({page})=>{const s=await backend(page,'lost-submit');await open(page);await page.getByRole('textbox',{name:'任务原文'}).fill('  真正保留原文\n  ');await page.getByRole('button',{name:'发送原文'}).click();await expect(page.getByRole('alert')).toContainText('请求结果未知');await page.reload();await expect(page.locator('.original-text')).toHaveText('  真正保留原文\n  ');await expect(page.getByText('实际阶段 · waiting_for_user')).toBeVisible();expect(s.turns).toBe(1);});
test('A2 default: old artifact hash refuses content and acceptance',async({page})=>{const s=await backend(page,'old-hash');await open(page);await expect(page.getByLabel('成果侧栏').getByRole('alert')).toContainText('固定版本不匹配');await expect(page.getByRole('button',{name:'接受整份成果'})).toBeDisabled();expect(s.accepts).toBe(0);});
test('A2 default: missing delivery is no result and never creates a task',async({page})=>{const s=await backend(page,'missing');await open(page);await expect(page.getByRole('button',{name:'读取当前成果与接受回执'})).toBeVisible();await expect(page.getByRole('button',{name:'接受整份成果'})).toBeDisabled();expect(s.turns).toBe(0);expect(s.accepts).toBe(0);});
test('A2 default: cancellation winning acceptance race is not reported as completed or retried',async({page})=>{const s=await backend(page,'cancel-race');await open(page);await expect(page.getByRole('button',{name:'接受整份成果'})).toBeEnabled();await page.getByRole('button',{name:'接受整份成果'}).click();await expect(page.getByText('实际阶段 · cancelled')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'接受整份成果'})).toBeDisabled();expect(s.accepts).toBe(1);expect(s.turns).toBe(0);});
test('A2 default: expired server cursor restarts and later page history is visible',async({page})=>{const s=await backend(page,'pagination');await open(page);await expect(page.getByLabel('会话侧栏').getByRole('button',{name:'第二页历史'})).toBeVisible();expect(s.listReads).toBe(4);expect(s.turns).toBe(0);});
test('A2 default: later login reads history but server refuses old-session acceptance; no automatic action',async({page})=>{const s=await backend(page,'identity');await open(page);await expect(page.getByRole('button',{name:'接受整份成果'})).toBeEnabled();s.session='session-two';await page.reload();await expect(page.getByRole('button',{name:'接受整份成果'})).toBeEnabled();expect(s.accepts).toBe(0);await page.getByRole('button',{name:'接受整份成果'}).click();await expect(page.getByRole('status').filter({hasText:'历史成果不能借新登录接受'})).toBeVisible();expect(s.accepts).toBe(1);});
