import {useEffect,useState,useSyncExternalStore} from 'react';
import {useSearchParams} from 'react-router';
import * as Dialog from '@radix-ui/react-dialog';
import {Plus,ArrowUp,MessageSquare,PanelLeft,RefreshCw,MoreHorizontal,ChevronDown,Square,Check, X, Sparkles,FolderOpen,LogOut,TriangleAlert} from 'lucide-react';
import {WorkspaceController} from './controller';
import type {ReviewPort} from '../review/port';
import {Review} from '../review/Review';
import {Markdown} from '../../components/Markdown';
import type {Schema} from '../../lib/api/types';
const statusLabel:Record<Schema['RunStatus'],string>={queued:'排队中',preparing:'正在理解任务',running:'努力奔跑中',verifying:'正在核验成果',waiting_for_user:'等待你确认',waiting_for_merge:'等待合并',completed:'已完成',failed:'运行失败',cancelled:'已取消'};
const stages:Record<Schema['RunStatus'],string>={queued:'queued',preparing:'preparing',running:'running',verifying:'verifying',waiting_for_user:'waiting_for_user',waiting_for_merge:'waiting_for_merge',completed:'completed',failed:'failed',cancelled:'cancelled'};
const itemLabels:Record<string,string>={understanding:'任务理解',agent_message:'UAW',plan:'计划',tool_call:'工具',command:'命令状态',file_change:'文件变更',approval:'待确认动作',user_control:'你的决定',artifact:'成果已登记',review:'核验',context_compression:'上下文记录'};
export function Workspace({controller,reviewPort}:{controller:WorkspaceController;reviewPort?:ReviewPort}){
 const s=useSyncExternalStore(controller.subscribe,controller.snapshot);const [params,setParams]=useSearchParams();
 const [newOpen,setNewOpen]=useState(false),[title,setTitle]=useState('新会话'),[model,setModel]=useState(''),[menu,setMenu]=useState(false);
 useEffect(()=>{void controller.start(params.get('conversation')??undefined);const off=controller.host.subscribe?.(()=>void controller.start());
  return()=>{off?.();controller.stop();};},[controller]);
 useEffect(()=>{if(s.active)setParams({conversation:s.active.id},{replace:true});},[s.active?.id]);
 const chosen=model||s.models[0]?.id||'';
 const understanding=s.draft?'发送后，将根据这段原文理解任务。':s.frame?.summary??(s.run?'正在等待实际任务理解…':'写下你的任务，从一段原文开始。');
 return <div className="workspace">
 <aside className={`sidebar ${menu?'mobile-open':''}`} aria-label="会话侧栏"><a href="/" className="brand"><span className="brand-mark">u</span><b>UAW</b><span>工作区</span></a>
 <button aria-label="新建会话" className="new-chat" disabled={!s.connected||s.busy} onClick={()=>setNewOpen(true)}><Plus size={16}/>新建会话<span>＋</span></button>
 <div className="sidebar-label">你的会话 <span>{s.conversations.length}</span><button aria-label="刷新会话列表" disabled={!s.connected||s.busy} onClick={()=>void controller.reconnect()}><RefreshCw size={12}/></button></div><nav>{s.conversations.map(c=><button key={c.id} className={`conversation ${c.id===s.active?.id?'active':''}`} disabled={s.busy} onClick={()=>{setMenu(false);void controller.open(c.id);}}><MessageSquare size={15}/><span>{c.title}</span>{c.id===s.active?.id&&<MoreHorizontal size={15}/>}</button>)}</nav>
 {!s.conversations.length&&<p className="sidebar-hint">创建会话，或刷新本人会话列表。<br/>服务器当前没有可显示的会话。</p>}
 <div className="sidebar-bottom"><div className="project-chip"><FolderOpen size={15}/><span>本机项目授权待接入</span></div><div className="account"><span className="avatar">U</span><div><strong>{s.connected?'已连接用户会话':'等待身份入口'}</strong><small>个人工作区</small></div><button aria-label="退出并清理本地草稿" onClick={()=>void controller.logout()}><LogOut size={15}/></button></div></div></aside>
 <main className="chat-panel"><header className="chat-header"><div><button className="mobile-toggle" aria-label="显示会话" onClick={()=>setMenu(!menu)}><PanelLeft size={18}/></button><span>{s.active?.title??'新的一页'}</span></div><div className="header-actions"><span className={`connection ${s.connected?'online':''}`}><i/>{s.connected?'已连接':'未连接'} · {s.transport}</span><button className="icon-button" aria-label="重新读取并连接" onClick={()=>void controller.reconnect()}><RefreshCw size={16}/></button></div></header>
 <div className="chat-scroll" aria-live="polite">{s.error&&<div className="notice" role="alert"><TriangleAlert size={16}/><span>{s.error}</span></div>}
 {!s.items.length?<div className="welcome"><span className="welcome-mark"><Sparkles size={29}/></span><p className="eyebrow">A LITTLE LESS BUSYWORK</p><h1>把想法交给这里，<br/>把时间留给你。</h1><p>整理材料，完成一份报告，或解决一个问题。<br/>保留你的原文，让每一步都有据可查。</p><div className="suggestions">{['整理材料，提炼要点','撰写一份清晰的报告','核验数据与引用'].map(t=><button key={t} disabled={!s.active} onClick={()=>controller.edit(t)}>{t}<ArrowUp size={13}/></button>)}</div></div>:<div className="messages">{s.items.map(item=><article key={item.id} className={`message ${item.type==='user_message'?'user':'assistant'}`} data-item-id={item.id}><div className="message-meta"><span className={item.type==='user_message'?'user-dot':'assistant-dot'}>{item.type==='user_message'?'你':'u'}</span><b>{item.type==='user_message'?'你':itemLabels[item.type]??`暂不支持的条目：${item.type}`}</b><small>v{item.revision} · {item.status}</small></div><div className="message-content">{item.type==='user_message'?<p className="original-text">{item.text}</p>:<Markdown text={item.text}/>}</div>{item.resource_refs.length>0&&<details className="message-refs"><summary>来源与版本 · {item.resource_refs.length}</summary>{item.resource_refs.map((r,i)=><p key={i}>{r.kind}/{r.id} · {r.version}</p>)}</details>}</article>)}</div>}
 {s.approvals.map(a=><section className="approval-card" key={a.id} aria-label="人工审批"><div><span className="approval-icon"><ShieldIcon/></span><strong>需要你确认</strong><span className="chip">{a.status}</span></div><h3>{a.summary}</h3><p>动作：{a.action_id} · {a.effect} · 版本 {a.revision}</p><details><summary>查看精确资源与参数摘要</summary><code>{a.arguments_hash}</code>{a.resource_refs.map((r,i)=><p key={i}>{r.kind}/{r.id}@{r.version}</p>)}</details><div className="approval-buttons"><button disabled={a.status!=='pending'||s.busy||!s.connected} onClick={()=>void controller.decide(a,'decline')}><X size={14}/>拒绝</button><button className="primary" disabled={a.status!=='pending'||s.busy||!s.connected} onClick={()=>void controller.decide(a,'approve_once')}><Check size={14}/>仅批准本次</button></div></section>)}
 </div><div className="composer-area">{s.run&&<div className="run-status"><span className={`status-dot ${s.run.status}`}/><b>{s.stopping?'正在停止':statusLabel[s.run.status]}</b><span>实际阶段 · {stages[s.run.status]}</span><small>v{s.run.revision}</small>{!['completed','failed','cancelled'].includes(s.run.status)&&<button disabled={s.busy||!s.connected||s.stopping} onClick={()=>void controller.cancel()}><Square size={11}/>停止</button>}</div>}
 <div className="understanding" aria-label="AI理解的任务"><div><Sparkles size={14}/><b>AI理解的任务</b>{s.frame&&!s.draft&&<span>v{s.frame.revision}</span>}</div><p>{understanding}</p><small>理解是提示，你的原文是执行基准。</small></div>
 <form className="composer" onSubmit={e=>{e.preventDefault();void controller.send();}}><textarea aria-label="任务原文" placeholder="告诉 UAW，你想完成什么…" value={s.draft} maxLength={131072} onChange={e=>controller.edit(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();void controller.send();}}}/><div className="composer-footer"><span className="model-chip"><span className="model-dot"/>{s.active?'本会话固定模型':'创建时选择模型'}<ChevronDown size={12}/></span><small>Ctrl / ⌘ + Enter 发送</small><button className="send-button" type="submit" aria-label="发送原文" disabled={!s.connected||!s.active||!s.draft.trim()||s.busy||!!s.recovery}><ArrowUp size={18}/></button></div></form><p className="composer-note">重要内容请结合来源与核验审阅。</p></div></main>
 <Review key={`${controller.host.session()?.identityKey}:${s.active?.id}`} items={s.items} run={s.run} port={reviewPort} identity={controller.host.session()?.identityKey??''} connected={s.connected} onAccepted={()=>void controller.reconnect()}/>
 <Dialog.Root open={newOpen} onOpenChange={setNewOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog"><Dialog.Title>开始一个新会话</Dialog.Title><Dialog.Description>选择已获准模型，本会话会保持这一选择。</Dialog.Description><label>会话名称<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={100}/></label><label>模型<select value={chosen} onChange={e=>setModel(e.target.value)}>{s.models.map(m=><option value={m.id} key={m.id}>{m.display_name}</option>)}</select></label><div className="dialog-actions"><Dialog.Close asChild><button>返回</button></Dialog.Close><button className="primary" disabled={!title.trim()||!chosen||s.busy} onClick={()=>{setNewOpen(false);void controller.create(title,chosen);}}>创建会话</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
function ShieldIcon(){return <Check size={17}/>;}
